/**
 * Mockup data standing in for the agent loop.
 *
 * The offers are real rows from the week of 17–22 Nov 2025 (see
 * new_columns.csv) — German titles, actual prices, actual validity windows —
 * so the UI is exercised with the messiness it will really get. Recipes,
 * costings and nutrition are hand-written; `calculation/` will produce them.
 */

import type { Market, Offer, Recipe, User } from './types'

const WEEK = { validFrom: '2025-11-17', validTill: '2025-11-22' }
/** Some offers only start later in the week. */
const SATURDAY = { validFrom: '2025-11-22', validTill: '2025-11-22' }
const THURSDAY = { validFrom: '2025-11-20', validTill: '2025-11-22' }

export const offers = {
  pumpkin: {
    title: 'Unsere Heimat – echt & gut Hokkaido Kürbis',
    ingredientEn: 'hokkaido pumpkin',
    category: 'Obst & Gemüse',
    priceCents: 111,
    dietType: 'vegan',
    ...WEEK,
  },
  gnocchi: {
    title: 'Henglein Kartoffel-Gnocchi',
    ingredientEn: 'potato gnocchi',
    category: 'Sonstiges',
    priceCents: 299,
    dietType: 'vegetarian',
    ...WEEK,
  },
  butter: {
    title: 'Weihenstephan Butter',
    ingredientEn: 'butter',
    category: 'Molkerei & Käse',
    priceCents: 179,
    dietType: 'vegetarian',
    ...WEEK,
  },
  granaPadano: {
    title: 'Grana Padano Riserva',
    ingredientEn: 'grana padano cheese',
    category: 'Molkerei & Käse',
    priceCents: 299,
    dietType: 'vegetarian',
    ...THURSDAY,
  },
  chickenThighs: {
    title: 'Frische Hähnchenschenkel',
    ingredientEn: 'fresh chicken thighs',
    category: 'Fleisch & Wurst',
    priceCents: 499,
    dietType: 'normal',
    ...SATURDAY,
  },
  soupVegetables: {
    title: 'Suppengrün',
    ingredientEn: 'soup vegetables',
    category: 'Obst & Gemüse',
    priceCents: 111,
    dietType: 'vegan',
    ...WEEK,
  },
  savoyCabbage: {
    title: 'Unsere Heimat – echt & gut Wirsing',
    ingredientEn: 'savoy cabbage',
    category: 'Obst & Gemüse',
    priceCents: 149,
    dietType: 'vegan',
    ...WEEK,
  },
  carrots: {
    title: 'EDEKA Bio Möhren',
    ingredientEn: 'carrots',
    category: 'Obst & Gemüse',
    priceCents: 129,
    dietType: 'vegan',
    ...WEEK,
  },
  pasta: {
    title: 'De Cecco italienische Teigwaren',
    ingredientEn: 'pasta',
    category: 'Grundnahrung',
    priceCents: 149,
    dietType: 'vegan',
    ...WEEK,
  },
  spinach: {
    title: 'Iglo Spinat',
    ingredientEn: 'spinach',
    category: 'Tiefkühl',
    priceCents: 179,
    dietType: 'vegan',
    ...WEEK,
  },
  tomatoes: {
    title: 'EDEKA Bio Rispentomaten',
    ingredientEn: 'vine tomatoes',
    category: 'Obst & Gemüse',
    priceCents: 149,
    dietType: 'vegan',
    ...WEEK,
  },
  nilePerch: {
    title: 'Viktoriaseebarschfilets',
    ingredientEn: 'Nile perch fillets',
    category: 'Fisch & Meeresfrüchte',
    priceCents: 199,
    dietType: 'normal',
    ...WEEK,
  },
  potatoes: {
    title: 'EDEKA Herzstücke Raclette Kartoffeln',
    ingredientEn: 'raclette potatoes',
    category: 'Obst & Gemüse',
    priceCents: 249,
    dietType: 'vegan',
    ...THURSDAY,
  },
  lambsLettuce: {
    title: 'Unsere Heimat – echt & gut Feldsalat',
    ingredientEn: "lamb's lettuce",
    category: 'Obst & Gemüse',
    priceCents: 249,
    dietType: 'vegan',
    ...SATURDAY,
  },
  vinegar: {
    title: 'Alnatura Bio Apfelessig naturtrüb',
    ingredientEn: 'organic apple cider vinegar',
    category: 'Sonstiges',
    priceCents: 179,
    dietType: 'vegan',
    ...WEEK,
  },
  skyr: {
    title: 'EDEKA Herzstücke High Protein Skyr Natur',
    ingredientEn: 'skyr yogurt',
    category: 'Molkerei & Käse',
    priceCents: 99,
    dietType: 'vegetarian',
    ...WEEK,
  },
  blueberries: {
    title: 'Heidelbeeren',
    ingredientEn: 'blueberries',
    category: 'Obst & Gemüse',
    priceCents: 399,
    dietType: 'vegan',
    ...WEEK,
  },
  muesli: {
    title: 'Kölln Müsli',
    ingredientEn: 'muesli',
    category: 'Grundnahrung',
    priceCents: 299,
    dietType: 'vegan',
    ...WEEK,
  },
  apples: {
    title: 'Elstar Äpfel',
    ingredientEn: 'elstar apples',
    category: 'Obst & Gemüse',
    priceCents: 79,
    dietType: 'vegan',
    ...WEEK,
  },
} satisfies Record<string, Offer>

export const recipes: Recipe[] = [
  {
    id: 'pumpkin-sage-gnocchi',
    title: 'Roast Hokkaido & Sage Gnocchi',
    summary:
      'Pan-crisped gnocchi with roast pumpkin, brown butter and a shower of Grana Padano.',
    servings: 2,
    minutes: 35,
    dietType: 'vegetarian',
    allergens: ['gluten', 'milk'],
    ingredients: [
      { name: 'hokkaido pumpkin', amount: '500 g', offer: offers.pumpkin },
      { name: 'potato gnocchi', amount: '500 g', offer: offers.gnocchi },
      { name: 'butter', amount: '30 g', offer: offers.butter },
      { name: 'grana padano cheese', amount: '40 g', offer: offers.granaPadano },
      { name: 'sage', amount: '8 leaves', regularPriceCents: 149 },
      { name: 'olive oil, salt, pepper', amount: 'to taste', pantry: true },
    ],
    steps: [
      'Heat the oven to 220 °C. Deseed the pumpkin and cut it into 2 cm wedges — no need to peel a Hokkaido.',
      'Toss with olive oil, salt and pepper, then roast for 20 minutes until the edges catch.',
      'Meanwhile melt the butter in a wide pan over medium heat and fry the gnocchi, undisturbed, until one side is golden — about 6 minutes.',
      'Add the sage leaves to the butter and let them crisp, 30 seconds.',
      'Fold the roast pumpkin through the gnocchi, then grate the Grana Padano over the top and serve straight from the pan.',
    ],
    cost: {
      totalCents: 556,
      perServingCents: 278,
      leftoverCents: 362,
      estimatedCents: 30,
      unpricedCount: 0,
    },
    nutrition: { kcal: 610, proteinG: 18, carbsG: 78, fatG: 24 },
    rationale:
      'Hokkaido at €1.11 is the cheapest vegetable on offer this week, and it needs neither peeling nor a second cooking step.',
    isFavourite: false,
    inMealPlan: false,
  },
  {
    id: 'chicken-savoy-traybake',
    title: 'One-Tray Chicken with Savoy & Root Veg',
    summary:
      'Chicken thighs roasted over soup greens and shredded savoy, so the vegetables cook in the fat.',
    servings: 4,
    minutes: 55,
    dietType: 'normal',
    allergens: ['celery'],
    ingredients: [
      { name: 'fresh chicken thighs', amount: '4 (approx. 800 g)', offer: offers.chickenThighs },
      { name: 'soup vegetables', amount: '1 bunch', offer: offers.soupVegetables },
      { name: 'savoy cabbage', amount: '½ head', offer: offers.savoyCabbage },
      { name: 'carrots', amount: '250 g', offer: offers.carrots },
      { name: 'paprika', amount: '1 tsp', regularPriceCents: null },
      { name: 'salt, oil', amount: 'to taste', pantry: true },
    ],
    steps: [
      'Heat the oven to 200 °C.',
      'Chop the soup greens and carrots into thumb-sized pieces and spread them over a deep tray. Shred the savoy and pile it on top.',
      'Rub the thighs with oil, salt and paprika and sit them skin-side up on the vegetables.',
      'Roast 45–50 minutes, until the skin is dark and the juices run clear.',
      'Rest 5 minutes, then spoon the pan juices back over the vegetables.',
    ],
    cost: {
      totalCents: 750,
      perServingCents: 188,
      leftoverCents: 138,
      estimatedCents: 0,
      unpricedCount: 1,
    },
    nutrition: { kcal: 520, proteinG: 41, carbsG: 18, fatG: 31 },
    rationale:
      'Four portions under €2 each. The soup greens are a €1.11 bundle that would otherwise be bought as three separate vegetables.',
    isFavourite: false,
    inMealPlan: false,
  },
  {
    id: 'spinach-tomato-pasta',
    title: 'Garlicky Spinach & Tomato Pasta',
    summary:
      'A fifteen-minute weeknight plate: frozen spinach wilted into blistered vine tomatoes.',
    servings: 3,
    minutes: 20,
    dietType: 'vegan',
    allergens: ['gluten'],
    ingredients: [
      { name: 'pasta', amount: '500 g', offer: offers.pasta },
      { name: 'spinach', amount: '450 g, frozen', offer: offers.spinach },
      { name: 'vine tomatoes', amount: '400 g', offer: offers.tomatoes },
      { name: 'garlic', amount: '3 cloves', pantry: true },
      { name: 'chilli flakes', amount: '1 pinch', regularPriceCents: null },
      { name: 'olive oil, salt', amount: 'to taste', pantry: true },
    ],
    steps: [
      'Boil the pasta in well-salted water.',
      'While it cooks, halve the tomatoes and blister them cut-side down in a hot, oiled pan without moving them.',
      'Add the sliced garlic and chilli, then the frozen spinach. Cover and let it thaw into the tomatoes, 5 minutes.',
      'Drain the pasta, keeping a cup of the water. Toss everything together, loosening with the pasta water until it clings.',
    ],
    cost: {
      totalCents: 477,
      perServingCents: 159,
      leftoverCents: 0,
      estimatedCents: 0,
      unpricedCount: 1,
    },
    nutrition: { kcal: 480, proteinG: 17, carbsG: 84, fatG: 8 },
    rationale:
      'Uses every pack completely — no leftovers to waste — and all three items are on offer for the full week.',
    isFavourite: false,
    inMealPlan: false,
  },
  {
    id: 'perch-lambs-lettuce',
    title: 'Pan-Fried Perch, Potatoes & Lamb’s Lettuce',
    summary:
      'Crisp-skinned fillets with buttered potatoes and a sharp apple-cider dressing.',
    servings: 2,
    minutes: 40,
    dietType: 'normal',
    allergens: ['fish', 'milk'],
    ingredients: [
      { name: 'Nile perch fillets', amount: '2 fillets', offer: offers.nilePerch },
      { name: 'raclette potatoes', amount: '600 g', offer: offers.potatoes },
      { name: "lamb's lettuce", amount: '150 g', offer: offers.lambsLettuce },
      { name: 'butter', amount: '20 g', offer: offers.butter },
      { name: 'organic apple cider vinegar', amount: '2 tbsp', offer: offers.vinegar },
      { name: 'oil, salt, pepper', amount: 'to taste', pantry: true },
    ],
    steps: [
      'Boil the potatoes whole in salted water, 20–25 minutes, then halve them and toss with the butter.',
      'Pat the fillets very dry and season. Fry skin-side down in hot oil, pressing flat for the first 30 seconds, 3–4 minutes until the skin releases.',
      'Flip and cook 1 minute more, then rest off the heat.',
      'Whisk the vinegar with oil, salt and pepper and dress the lamb’s lettuce at the last moment.',
      'Plate the potatoes, the fish on top, the salad alongside.',
    ],
    cost: {
      totalCents: 620,
      perServingCents: 310,
      leftoverCents: 435,
      estimatedCents: 0,
      unpricedCount: 0,
    },
    nutrition: { kcal: 540, proteinG: 38, carbsG: 42, fatG: 22 },
    rationale:
      'The perch is €1.99 for two fillets. Note the lamb’s lettuce and potatoes are Saturday-and-Thursday offers — shop late in the week for this one.',
    isFavourite: false,
    inMealPlan: false,
  },
  {
    id: 'blueberry-skyr-bowl',
    title: 'Blueberry Skyr Breakfast Bowl',
    summary:
      'High-protein skyr under blueberries, grated apple and toasted muesli. Five minutes, no cooking.',
    servings: 2,
    minutes: 5,
    dietType: 'vegetarian',
    allergens: ['milk', 'gluten'],
    ingredients: [
      { name: 'skyr yogurt', amount: '450 g', offer: offers.skyr },
      { name: 'blueberries', amount: '125 g', offer: offers.blueberries },
      { name: 'muesli', amount: '100 g', offer: offers.muesli },
      { name: 'elstar apples', amount: '1 apple', offer: offers.apples },
      { name: 'cinnamon, honey', amount: 'to taste', regularPriceCents: null },
    ],
    steps: [
      'Toast the muesli dry in a pan for 2 minutes, until it smells nutty.',
      'Coarsely grate the apple — skin on.',
      'Spoon the skyr into two bowls and top with the apple, blueberries and muesli.',
      'Finish with cinnamon and a thread of honey.',
    ],
    cost: {
      totalCents: 399,
      perServingCents: 200,
      leftoverCents: 477,
      estimatedCents: 0,
      unpricedCount: 1,
    },
    nutrition: { kcal: 340, proteinG: 21, carbsG: 48, fatG: 6 },
    rationale:
      'Skyr at €0.99 carries 21 g of protein per serving — the cheapest protein per euro in this week’s offers.',
    isFavourite: false,
    inMealPlan: false,
  },
]

/**
 * Recipes the mock hands out when the user asks for new ones. Built on the
 * same week's offers, so the shopping list still makes sense.
 */
export const extraRecipes: Recipe[] = [
  {
    id: 'hokkaido-soup',
    title: 'Velvet Hokkaido Soup',
    summary: 'Pumpkin and soup greens blended smooth, finished with a spoon of skyr.',
    servings: 4,
    minutes: 40,
    dietType: 'vegetarian',
    allergens: ['milk', 'celery'],
    ingredients: [
      { name: 'hokkaido pumpkin', amount: '1 kg', offer: offers.pumpkin },
      { name: 'soup vegetables', amount: '1 bunch', offer: offers.soupVegetables },
      { name: 'skyr yogurt', amount: '150 g', offer: offers.skyr },
      { name: 'vegetable stock', amount: '1 l', regularPriceCents: 179 },
      { name: 'nutmeg', amount: '1 pinch', regularPriceCents: null },
      { name: 'salt', amount: 'to taste', pantry: true },
    ],
    steps: [
      'Chop the pumpkin and soup greens roughly — the pumpkin skin can stay on.',
      'Cover with stock and simmer 25 minutes until everything is soft.',
      'Blend smooth and season with salt and nutmeg.',
      'Serve with a spoon of skyr swirled through each bowl.',
    ],
    cost: { totalCents: 434, perServingCents: 109, leftoverCents: 66, estimatedCents: 179, unpricedCount: 1 },
    nutrition: { kcal: 190, proteinG: 8, carbsG: 30, fatG: 3 },
    rationale: 'Four bowls for under €3, and it uses the whole pumpkin.',
    isFavourite: false,
    inMealPlan: false,
  },
  {
    id: 'potato-spinach-hash',
    title: 'Potato & Spinach Hash with Fried Eggs',
    summary: 'Crisp potato cubes and garlicky spinach, topped with a runny egg.',
    servings: 2,
    minutes: 30,
    dietType: 'vegetarian',
    allergens: ['eggs'],
    ingredients: [
      { name: 'raclette potatoes', amount: '500 g', offer: offers.potatoes },
      { name: 'spinach', amount: '225 g, frozen', offer: offers.spinach },
      { name: 'eggs', amount: '2', regularPriceCents: 299 },
      { name: 'garlic, oil, salt', amount: 'to taste', pantry: true },
    ],
    steps: [
      'Dice the potatoes and fry in oil over medium heat for 15 minutes, turning now and then.',
      'Add the garlic and frozen spinach and cook until the spinach has thawed and the pan is dry.',
      'Make two hollows, crack in the eggs, cover and cook 3–4 minutes.',
    ],
    cost: { totalCents: 357, perServingCents: 179, leftoverCents: 131, estimatedCents: 60, unpricedCount: 0 },
    nutrition: { kcal: 420, proteinG: 18, carbsG: 46, fatG: 17 },
    rationale: 'A fridge-friendly dinner: eggs and potatoes carry it.',
    isFavourite: false,
    inMealPlan: false,
  },
  {
    id: 'savoy-carrot-noodles',
    title: 'Savoy & Carrot Noodle Stir-Fry',
    summary: 'Pasta tossed with shredded savoy and carrot ribbons in a soy-garlic glaze.',
    servings: 3,
    minutes: 20,
    dietType: 'vegan',
    allergens: ['gluten', 'soy'],
    ingredients: [
      { name: 'pasta', amount: '300 g', offer: offers.pasta },
      { name: 'savoy cabbage', amount: '½ head', offer: offers.savoyCabbage },
      { name: 'carrots', amount: '250 g', offer: offers.carrots },
      { name: 'soy sauce', amount: '3 tbsp', regularPriceCents: 249 },
      { name: 'garlic, oil', amount: 'to taste', pantry: true },
    ],
    steps: [
      'Cook the pasta; meanwhile shred the savoy and peel the carrots into ribbons.',
      'Stir-fry the vegetables in a very hot pan for 4 minutes.',
      'Add garlic and soy sauce, then toss the drained pasta through.',
    ],
    cost: { totalCents: 308, perServingCents: 103, leftoverCents: 164, estimatedCents: 45, unpricedCount: 0 },
    nutrition: { kcal: 430, proteinG: 14, carbsG: 82, fatG: 6 },
    rationale: 'Uses the other half of the savoy from the traybake.',
    isFavourite: false,
    inMealPlan: false,
  },
  {
    id: 'perch-tomato-bake',
    title: 'Perch & Tomato Traybake',
    summary: 'Fillets roasted on vine tomatoes and potatoes, all on one tray.',
    servings: 2,
    minutes: 35,
    dietType: 'pescetarian',
    allergens: ['fish'],
    ingredients: [
      { name: 'Nile perch fillets', amount: '2 fillets', offer: offers.nilePerch },
      { name: 'vine tomatoes', amount: '400 g', offer: offers.tomatoes },
      { name: 'raclette potatoes', amount: '400 g', offer: offers.potatoes },
      { name: 'lemon', amount: '1', regularPriceCents: 59 },
      { name: 'olive oil, salt', amount: 'to taste', pantry: true },
    ],
    steps: [
      'Slice the potatoes thinly and roast at 220 °C for 15 minutes.',
      'Add the tomatoes and the seasoned fillets on top.',
      'Roast 12 more minutes and finish with lemon.',
    ],
    cost: { totalCents: 573, perServingCents: 287, leftoverCents: 83, estimatedCents: 59, unpricedCount: 0 },
    nutrition: { kcal: 460, proteinG: 36, carbsG: 40, fatG: 15 },
    rationale: 'Fish twice a week for under €2.60 a plate.',
    isFavourite: false,
    inMealPlan: false,
  },
]

export const markets: Market[] = [
  { id: 1, chain: 'edeka', marketId: '10001604', name: 'EDEKA Frank', street: 'Erlachstraße 45', postalCode: '74223', city: 'Flein' },
  { id: 2, chain: 'edeka', marketId: '10000871', name: 'EDEKA Hieber', street: 'Bahnhofstraße 12', postalCode: '79539', city: 'Lörrach' },
  { id: 3, chain: 'edeka', marketId: '10002233', name: 'EDEKA Kempf', street: 'Hauptstraße 8', postalCode: '74074', city: 'Heilbronn' },
  { id: 4, chain: 'aldi', marketId: '1588161426582123', name: 'ALDI SÜD', street: null, postalCode: null, city: 'all branches' },
]

export const user: User = {
  name: 'Nga',
  email: 'nga@arkadia.hn',
  dietType: 'normal',
  householdSize: 2,
  weeklyBudgetCents: 4000,
  allergens: ['nuts'],
  homeMarkets: [],
  cuisines: ['Italian', 'German'],
  whiteList: ['pumpkin', 'spinach'],
  blackList: ['coriander'],
  age: null,
  gender: null,
  weekTimeAvailability: [30, 30, 45, 30, 60, 90, 60],
  mealTypes: ['lunch', 'dinner'],
}
