"""baseline: the schema as of September 2026

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 20:07:36.625521
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('food_type', sa.String(length=50), nullable=True),
    sa.Column('serving_size', sa.Float(), nullable=True),
    sa.Column('serving_unit', sa.String(length=20), nullable=True),
    sa.Column('kcal_per_100', sa.Float(), nullable=True),
    sa.Column('protein_per_100', sa.Float(), nullable=True),
    sa.Column('carbs_per_100', sa.Float(), nullable=True),
    sa.Column('fat_per_100', sa.Float(), nullable=True),
    sa.Column('allergens', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cooking_appliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cuisine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=450), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('normalization_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('ingredient_en', sa.String(length=120), nullable=True),
    sa.Column('can_cook', sa.Boolean(), nullable=True),
    sa.Column('use_baking', sa.Boolean(), nullable=True),
    sa.Column('use_drinks', sa.Boolean(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalization_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normalization_cache_raw_name'), ['raw_name'], unique=True)

    op.create_table('recipe_fetch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=20), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('query_key', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.String(length=10), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('returned', sa.Integer(), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supermarket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weekly_refresh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=60), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store', 'week_start', name='uq_refresh_week')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supermarket_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('street', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['supermarket_id'], ['supermarket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id')
    )
    op.create_table('generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=10), server_default='weekly', nullable=False),
    sa.Column('diet_type', sa.String(length=20), nullable=True),
    sa.Column('pantry_items', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('use', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('waste_grams', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('nutrition_ok', sa.Boolean(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('cuisine_id', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('diet_type', sa.String(length=20), nullable=True),
    sa.Column('course', sa.String(length=20), nullable=True),
    sa.Column('dish_kind', sa.String(length=30), nullable=True),
    sa.Column('main_ingredient', sa.String(length=80), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.Column('cooking_time', sa.Integer(), nullable=True),
    sa.Column('waiting_time', sa.Integer(), nullable=True),
    sa.Column('total_kcal', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('method_checked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_recipe_source')
    )
    op.create_table('user_preference',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('diet_type', sa.String(length=20), nullable=True),
    sa.Column('cuisines', sa.JSON(), nullable=True),
    sa.Column('allergens', sa.JSON(), nullable=True),
    sa.Column('black_list', sa.JSON(), nullable=True),
    sa.Column('white_list', sa.JSON(), nullable=True),
    sa.Column('health_goal', sa.String(length=120), nullable=True),
    sa.Column('week_time_availability', sa.JSON(), nullable=True),
    sa.Column('meal_types', sa.JSON(), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('weekly_budget_cents', sa.Integer(), nullable=True),
    sa.Column('fav_supermarket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fav_supermarket_id'], ['supermarket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('favourite_recipe',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_cache.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_preference.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.create_table('generation_recipe',
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_cache.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('generation_id', 'recipe_id')
    )
    op.create_table('meal_plan_recipe',
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_cache.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('generation_id', 'recipe_id')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('price_per_unit_unit', sa.String(length=10), nullable=True),
    sa.Column('quantity_amount', sa.Float(), nullable=True),
    sa.Column('quantity_unit', sa.String(length=20), nullable=True),
    sa.Column('quantity_basis', sa.String(length=20), nullable=True),
    sa.Column('pack_count', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_till', sa.Date(), nullable=True),
    sa.Column('ingredient_en', sa.String(length=120), nullable=True),
    sa.Column('canonical_ingredient_id', sa.Integer(), nullable=True),
    sa.Column('can_cook', sa.Boolean(), nullable=True),
    sa.Column('use_baking', sa.Boolean(), nullable=True),
    sa.Column('use_drinks', sa.Boolean(), nullable=True),
    sa.Column('meal_role', sa.String(length=20), nullable=True),
    sa.Column('base_ingredient', sa.String(length=120), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['canonical_ingredient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address_id', 'title', 'valid_from', name='uq_offer_run')
    )
    op.create_table('offer_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('price_per_unit_unit', sa.String(length=10), nullable=True),
    sa.Column('quantity_amount', sa.Float(), nullable=True),
    sa.Column('quantity_unit', sa.String(length=20), nullable=True),
    sa.Column('quantity_basis', sa.String(length=20), nullable=True),
    sa.Column('pack_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_appliance',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['cooking_appliance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_cache.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'appliance_id')
    )
    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('canonical_ingredient_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['canonical_ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_cache.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_home_market',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_preference.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'address_id')
    )
    op.create_table('user_recipe_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_cache.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_item')
    op.drop_table('user_recipe_feedback')
    op.drop_table('user_home_market')
    op.drop_table('recipe_ingredient')
    op.drop_table('recipe_appliance')
    op.drop_table('offer_history')
    op.drop_table('offer')
    op.drop_table('meal_plan_recipe')
    op.drop_table('generation_recipe')
    op.drop_table('favourite_recipe')
    op.drop_table('user_preference')
    op.drop_table('recipe_cache')
    op.drop_table('generation')
    op.drop_table('address')
    op.drop_table('weekly_refresh')
    op.drop_table('user_account')
    op.drop_table('supermarket')
    op.drop_table('recipe_fetch')
    with op.batch_alter_table('normalization_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalization_cache_raw_name'))

    op.drop_table('normalization_cache')
    op.drop_table('cuisine')
    op.drop_table('cooking_appliance')
    op.drop_table('canonical_ingredient')
    # ### end Alembic commands ###
