"""the critic's assessment and rounds on each plan

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 20:08:48.120538
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rounds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation', schema=None) as batch_op:
        batch_op.drop_column('rounds')
        batch_op.drop_column('assessment')

    # ### end Alembic commands ###
